const T={
es:{eyebrow:"MENÚ DIGITAL · CABO NIGHTLIFE",welcome:"ELIGE TU EXPERIENCIA",subtitle:"Bebidas, hookahs y comida para disfrutar la noche.",drinks:"BEBIDAS Y BOTELLAS",hookahs:"HOOKAHS",food:"ALIMENTOS",pricesNote:"Precios independientes en MXN y USD.",drinksTitle:"Bebidas y botellas",hookahTitle:"Hookahs",flavorsTitle:"Sabores disponibles",foodTitle:"Alimentos",empty:"No se encontraron productos.",footer:"BUEN AMBIENTE · GRAN MÚSICA · NOCHES INOLVIDABLES",disclaimer:"Consulta disponibilidad con nuestro equipo. Los precios pueden cambiar sin previo aviso.",bottle:"Botella",pour:"Copa",mxn:"MXN",usd:"USD",confirm:"Por confirmar",search:"Buscar producto...",categories:{Rum:"Ron", "Cognac & Brandy":"Coñac y brandy",Gin:"Ginebra",Whisky:"Whisky",Tequila:"Tequila",Vodka:"Vodka"}},
en:{eyebrow:"DIGITAL MENU · CABO NIGHTLIFE",welcome:"CHOOSE YOUR EXPERIENCE",subtitle:"Drinks, hookahs and food to enjoy the night.",drinks:"DRINKS & BOTTLES",hookahs:"HOOKAHS",food:"FOOD",pricesNote:"Independent prices in MXN and USD.",drinksTitle:"Drinks & Bottles",hookahTitle:"Hookahs",flavorsTitle:"Available Flavors",foodTitle:"Food Menu",empty:"No products found.",footer:"GOOD VIBES · GREAT MUSIC · UNFORGETTABLE NIGHTS",disclaimer:"Please check availability with our team. Prices may change without notice.",bottle:"Bottle",pour:"Glass",mxn:"MXN",usd:"USD",confirm:"To be confirmed",search:"Search products...",categories:{Rum:"Rum","Cognac & Brandy":"Cognac & Brandy",Gin:"Gin",Whisky:"Whisky",Tequila:"Tequila",Vodka:"Vodka"}}
};
let lang="es",activeTab="drinks";
const money=(v,currency)=>v?`${currency==="MXN"?"$":"US$"}${Number(v).toLocaleString("en-US")}`:T[lang].confirm;
function setLanguage(next){lang=next;document.documentElement.lang=lang;document.querySelectorAll("[data-i18n]").forEach(el=>{const k=el.dataset.i18n;if(T[lang][k])el.textContent=T[lang][k]});document.getElementById("esBtn").classList.toggle("active",lang==="es");document.getElementById("enBtn").classList.toggle("active",lang==="en");document.getElementById("search").placeholder=T[lang].search;renderAll();}
function renderDrinks(){const root=document.getElementById("drinkGroups");root.innerHTML="";const groups={};BALAM_MENU.drinks.forEach(p=>(groups[p.category]??=[]).push(p));Object.entries(groups).forEach(([category,items])=>{const group=document.createElement("div");group.className="drink-group";group.innerHTML=`<h3 class="group-title">${T[lang].categories[category]||category}</h3><div class="drink-head"><span></span><span>${T[lang].bottle}<br>MXN</span><span>${T[lang].pour}<br>MXN</span><span>${T[lang].bottle}<br>USD</span><span>${T[lang].pour}<br>USD</span></div>`;items.forEach(p=>{const row=document.createElement("div");row.className="drink-row searchable";row.dataset.search=(p.name_es+" "+p.name_en+" "+category).toLowerCase();row.innerHTML=`<span class="product-name">${lang==="es"?p.name_es:p.name_en}</span><span class="price">${money(p.bottle_mxn,"MXN")}</span><span class="price">${money(p.pour_mxn,"MXN")}</span><span class="price">${money(p.bottle_usd,"USD")}</span><span class="price">${money(p.pour_usd,"USD")}</span>`;group.appendChild(row)});root.appendChild(group)});}
function renderHookahs(){document.getElementById("hookahPrices").innerHTML=BALAM_MENU.hookahs.map(p=>`<article class="price-card searchable" data-search="${p.name_es.toLowerCase()} ${p.name_en.toLowerCase()}"><h3>${lang==="es"?p.name_es:p.name_en}</h3><div class="price-pair"><span>MXN</span><strong>${money(p.price_mxn,"MXN")}</strong></div><div class="price-pair"><span>USD</span><strong>${money(p.price_usd,"USD")}</strong></div></article>`).join("");document.getElementById("flavorGroups").innerHTML=BALAM_MENU.flavors.map(g=>`<article class="flavor-card searchable" data-search="${g.items.flat().join(" ").toLowerCase()} ${g.group_es.toLowerCase()} ${g.group_en.toLowerCase()}"><h3>${lang==="es"?g.group_es:g.group_en}</h3><ul>${g.items.map(i=>`<li>${lang==="es"?i[0]:i[1]}</li>`).join("")}</ul></article>`).join("");}
function renderFood(){document.getElementById("foodGrid").innerHTML=BALAM_MENU.food.map(p=>`<article class="food-card searchable" data-search="${(p.name_es+" "+p.name_en+" "+p.desc_es+" "+p.desc_en).toLowerCase()}"><h3>${lang==="es"?p.name_es:p.name_en}</h3><p>${lang==="es"?p.desc_es:p.desc_en}</p><div class="food-price">${p.price_mxn?money(p.price_mxn,"MXN"):""}${p.price_mxn&&p.price_usd?" · ":""}${p.price_usd?money(p.price_usd,"USD"):""}<small>${p.price_mxn?"MXN":""}${p.price_mxn&&p.price_usd?" / ":""}${p.price_usd?"USD":""}${!p.price_mxn?" · "+(lang==="es"?"Precio MXN pendiente":"MXN price pending"):""}</small></div></article>`).join("");}
function renderAll(){renderDrinks();renderHookahs();renderFood();filterSearch();}
function filterSearch(){const q=document.getElementById("search").value.trim().toLowerCase();let count=0;document.querySelectorAll(".panel.active .searchable").forEach(el=>{const match=!q||(el.dataset.search||el.textContent.toLowerCase()).includes(q);el.classList.toggle("hidden-by-search",!match);if(match)count++});document.getElementById("empty").hidden=count>0;}
document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>{activeTab=b.dataset.tab;document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".panel").forEach(x=>x.classList.toggle("active",x.id===activeTab));document.getElementById("search").value="";filterSearch();window.scrollTo({top:document.querySelector(".tabs").offsetTop,behavior:"smooth"})}));
document.getElementById("esBtn").addEventListener("click",()=>setLanguage("es"));document.getElementById("enBtn").addEventListener("click",()=>setLanguage("en"));document.getElementById("search").addEventListener("input",filterSearch);setLanguage("es");
